/**
 * Copyright (C) 2014 - present by OpenGamma Inc. and the OpenGamma group of companies
 *
 * Please see distribution for license.
 */
  // NOTE: This code is autogenerated, see src/generator/scripts/testgen.m
  
 #include "gtest/gtest.h"
 #include "terminal.hh"
 #include "execution.hh"
 #include "dispatch.hh"
 #include "testnodes.hh"
 
 using namespace std;
 using namespace librdag;
 using namespace testnodes;
 using ::testing::TestWithParam;
 using ::testing::Values;
 
   /*
    * Check MINUS node behaves
    */
 
   BINARY_NODE_TEST_SETUP(MINUS)
 
   INSTANTIATE_NODE_TEST_CASE_P(MINUSTests,MINUS,
     Values
     (
       // real scalar minus real scalar
new CheckBinary<MINUS>(OGRealScalar::create(      7.0), OGRealScalar::create(      7.0), OGRealScalar::create(      0.0), MATHSEQUAL),
// real scalar minus complex scalar
new CheckBinary<MINUS>(OGRealScalar::create(      7.0), OGComplexScalar::create({      5.0,     11.0}), OGComplexScalar::create({      2.0,    -11.0}), MATHSEQUAL),
// complex scalar minus real scalar
new CheckBinary<MINUS>(OGComplexScalar::create({      5.0,     11.0}), OGRealScalar::create(      7.0), OGComplexScalar::create({     -2.0,     11.0}), MATHSEQUAL),
// complex scalar minus complex scalar
new CheckBinary<MINUS>(OGComplexScalar::create({      5.0,     11.0}), OGComplexScalar::create({      5.0,     11.0}), OGRealScalar::create(      0.0), MATHSEQUAL),
// real scalar minus real length 4 column vector
new CheckBinary<MINUS>(OGRealScalar::create(      7.0), OGRealDenseMatrix::create({{1.0},{2.0},{3.0},{4.0}}), OGRealDenseMatrix::create({{6.0},{5.0},{4.0},{3.0}}), MATHSEQUAL),
// real scalar minus real length 4 row vector
new CheckBinary<MINUS>(OGRealScalar::create(      7.0), OGRealDenseMatrix::create({{4.0,3.0,2.0,1.0}}), OGRealDenseMatrix::create({{3.0,4.0,5.0,6.0}}), MATHSEQUAL),
// complex scalar minus real length 4 column vector
new CheckBinary<MINUS>(OGComplexScalar::create({      5.0,     11.0}), OGRealDenseMatrix::create({{1.0},{2.0},{3.0},{4.0}}), OGComplexDenseMatrix::create({{{4.0,11.0}},{{3.0,11.0}},{{2.0,11.0}},{{1.0,11.0}}}), MATHSEQUAL),
// complex scalar minus real length 4 row vector
new CheckBinary<MINUS>(OGComplexScalar::create({      5.0,     11.0}), OGRealDenseMatrix::create({{4.0,3.0,2.0,1.0}}), OGComplexDenseMatrix::create({{{1.0,11.0},{2.0,11.0},{3.0,11.0},{4.0,11.0}}}), MATHSEQUAL),
// real length 4 column vector minus real scalar
new CheckBinary<MINUS>(OGRealDenseMatrix::create({{1.0},{2.0},{3.0},{4.0}}), OGRealScalar::create(      7.0), OGRealDenseMatrix::create({{-6.0},{-5.0},{-4.0},{-3.0}}), MATHSEQUAL),
// real length 4 row vector minus real scalar
new CheckBinary<MINUS>(OGRealDenseMatrix::create({{4.0,3.0,2.0,1.0}}), OGRealScalar::create(      7.0), OGRealDenseMatrix::create({{-3.0,-4.0,-5.0,-6.0}}), MATHSEQUAL),
// real length 4 column vector minus complex scalar
new CheckBinary<MINUS>(OGRealDenseMatrix::create({{1.0},{2.0},{3.0},{4.0}}), OGComplexScalar::create({      5.0,     11.0}), OGComplexDenseMatrix::create({{{-4.0,-11.0}},{{-3.0,-11.0}},{{-2.0,-11.0}},{{-1.0,-11.0}}}), MATHSEQUAL),
// real length 4 row vector minus complex scalar
new CheckBinary<MINUS>(OGRealDenseMatrix::create({{4.0,3.0,2.0,1.0}}), OGComplexScalar::create({      5.0,     11.0}), OGComplexDenseMatrix::create({{{-1.0,-11.0},{-2.0,-11.0},{-3.0,-11.0},{-4.0,-11.0}}}), MATHSEQUAL),
// real scalar minus complex length 4 column vector
new CheckBinary<MINUS>(OGRealScalar::create(      7.0), OGComplexDenseMatrix::create({{{1.0,4.0}},{{2.0,3.0}},{{3.0,2.0}},{{4.0,1.0}}}), OGComplexDenseMatrix::create({{{6.0,-4.0}},{{5.0,-3.0}},{{4.0,-2.0}},{{3.0,-1.0}}}), MATHSEQUAL),
// real scalar minus complex length 4 row vector
new CheckBinary<MINUS>(OGRealScalar::create(      7.0), OGComplexDenseMatrix::create({{{4.0,1.0},{3.0,2.0},{2.0,3.0},{1.0,4.0}}}), OGComplexDenseMatrix::create({{{3.0,-1.0},{4.0,-2.0},{5.0,-3.0},{6.0,-4.0}}}), MATHSEQUAL),
// complex scalar minus complex length 4 column vector
new CheckBinary<MINUS>(OGComplexScalar::create({      5.0,     11.0}), OGComplexDenseMatrix::create({{{1.0,4.0}},{{2.0,3.0}},{{3.0,2.0}},{{4.0,1.0}}}), OGComplexDenseMatrix::create({{{4.0,7.0}},{{3.0,8.0}},{{2.0,9.0}},{{1.0,10.0}}}), MATHSEQUAL),
// complex scalar minus complex length 4 row vector
new CheckBinary<MINUS>(OGComplexScalar::create({      5.0,     11.0}), OGComplexDenseMatrix::create({{{4.0,1.0},{3.0,2.0},{2.0,3.0},{1.0,4.0}}}), OGComplexDenseMatrix::create({{{1.0,10.0},{2.0,9.0},{3.0,8.0},{4.0,7.0}}}), MATHSEQUAL),
// complex length 4 column vector minus real scalar
new CheckBinary<MINUS>(OGComplexDenseMatrix::create({{{1.0,4.0}},{{2.0,3.0}},{{3.0,2.0}},{{4.0,1.0}}}), OGRealScalar::create(      7.0), OGComplexDenseMatrix::create({{{-6.0,4.0}},{{-5.0,3.0}},{{-4.0,2.0}},{{-3.0,1.0}}}), MATHSEQUAL),
// complex length 4 row vector minus real scalar
new CheckBinary<MINUS>(OGComplexDenseMatrix::create({{{4.0,1.0},{3.0,2.0},{2.0,3.0},{1.0,4.0}}}), OGRealScalar::create(      7.0), OGComplexDenseMatrix::create({{{-3.0,1.0},{-4.0,2.0},{-5.0,3.0},{-6.0,4.0}}}), MATHSEQUAL),
// complex length 4 column vector minus complex scalar
new CheckBinary<MINUS>(OGComplexDenseMatrix::create({{{1.0,4.0}},{{2.0,3.0}},{{3.0,2.0}},{{4.0,1.0}}}), OGComplexScalar::create({      5.0,     11.0}), OGComplexDenseMatrix::create({{{-4.0,-7.0}},{{-3.0,-8.0}},{{-2.0,-9.0}},{{-1.0,-10.0}}}), MATHSEQUAL),
// complex length 4 row vector minus complex scalar
new CheckBinary<MINUS>(OGComplexDenseMatrix::create({{{4.0,1.0},{3.0,2.0},{2.0,3.0},{1.0,4.0}}}), OGComplexScalar::create({      5.0,     11.0}), OGComplexDenseMatrix::create({{{-1.0,-10.0},{-2.0,-9.0},{-3.0,-8.0},{-4.0,-7.0}}}), MATHSEQUAL),
// real scalar minus real 5x4 matrix
new CheckBinary<MINUS>(OGRealScalar::create(      7.0), OGRealDenseMatrix::create({{1.0,3.0,2.0,1.0},{2.0,1.0,3.0,2.0},{3.0,2.0,1.0,3.0},{4.0,3.0,2.0,1.0},{5.0,4.0,3.0,2.0}}), OGRealDenseMatrix::create({{6.0,4.0,5.0,6.0},{5.0,6.0,4.0,5.0},{4.0,5.0,6.0,4.0},{3.0,4.0,5.0,6.0},{2.0,3.0,4.0,5.0}}), MATHSEQUAL),
// real scalar minus real 4x5 matrix
new CheckBinary<MINUS>(OGRealScalar::create(      7.0), OGRealDenseMatrix::create({{1.0,4.0,3.0,2.0,1.0},{2.0,1.0,4.0,3.0,2.0},{3.0,2.0,1.0,4.0,3.0},{4.0,3.0,2.0,1.0,4.0}}), OGRealDenseMatrix::create({{6.0,3.0,4.0,5.0,6.0},{5.0,6.0,3.0,4.0,5.0},{4.0,5.0,6.0,3.0,4.0},{3.0,4.0,5.0,6.0,3.0}}), MATHSEQUAL),
// complex scalar minus real 5x4 matrix
new CheckBinary<MINUS>(OGComplexScalar::create({      5.0,     11.0}), OGRealDenseMatrix::create({{1.0,3.0,2.0,1.0},{2.0,1.0,3.0,2.0},{3.0,2.0,1.0,3.0},{4.0,3.0,2.0,1.0},{5.0,4.0,3.0,2.0}}), OGComplexDenseMatrix::create({{{4.0,11.0},{2.0,11.0},{3.0,11.0},{4.0,11.0}},{{3.0,11.0},{4.0,11.0},{2.0,11.0},{3.0,11.0}},{{2.0,11.0},{3.0,11.0},{4.0,11.0},{2.0,11.0}},{{1.0,11.0},{2.0,11.0},{3.0,11.0},{4.0,11.0}},{{0.0,11.0},{1.0,11.0},{2.0,11.0},{3.0,11.0}}}), MATHSEQUAL),
// complex scalar minus real 4x5 matrix
new CheckBinary<MINUS>(OGComplexScalar::create({      5.0,     11.0}), OGRealDenseMatrix::create({{1.0,4.0,3.0,2.0,1.0},{2.0,1.0,4.0,3.0,2.0},{3.0,2.0,1.0,4.0,3.0},{4.0,3.0,2.0,1.0,4.0}}), OGComplexDenseMatrix::create({{{4.0,11.0},{1.0,11.0},{2.0,11.0},{3.0,11.0},{4.0,11.0}},{{3.0,11.0},{4.0,11.0},{1.0,11.0},{2.0,11.0},{3.0,11.0}},{{2.0,11.0},{3.0,11.0},{4.0,11.0},{1.0,11.0},{2.0,11.0}},{{1.0,11.0},{2.0,11.0},{3.0,11.0},{4.0,11.0},{1.0,11.0}}}), MATHSEQUAL),
// real 5x4 matrix minus real scalar
new CheckBinary<MINUS>(OGRealDenseMatrix::create({{1.0,3.0,2.0,1.0},{2.0,1.0,3.0,2.0},{3.0,2.0,1.0,3.0},{4.0,3.0,2.0,1.0},{5.0,4.0,3.0,2.0}}), OGRealScalar::create(      7.0), OGRealDenseMatrix::create({{-6.0,-4.0,-5.0,-6.0},{-5.0,-6.0,-4.0,-5.0},{-4.0,-5.0,-6.0,-4.0},{-3.0,-4.0,-5.0,-6.0},{-2.0,-3.0,-4.0,-5.0}}), MATHSEQUAL),
// real 4x5 matrix minus real scalar
new CheckBinary<MINUS>(OGRealDenseMatrix::create({{1.0,4.0,3.0,2.0,1.0},{2.0,1.0,4.0,3.0,2.0},{3.0,2.0,1.0,4.0,3.0},{4.0,3.0,2.0,1.0,4.0}}), OGRealScalar::create(      7.0), OGRealDenseMatrix::create({{-6.0,-3.0,-4.0,-5.0,-6.0},{-5.0,-6.0,-3.0,-4.0,-5.0},{-4.0,-5.0,-6.0,-3.0,-4.0},{-3.0,-4.0,-5.0,-6.0,-3.0}}), MATHSEQUAL),
// real 5x4 matrix minus complex scalar
new CheckBinary<MINUS>(OGRealDenseMatrix::create({{1.0,3.0,2.0,1.0},{2.0,1.0,3.0,2.0},{3.0,2.0,1.0,3.0},{4.0,3.0,2.0,1.0},{5.0,4.0,3.0,2.0}}), OGComplexScalar::create({      5.0,     11.0}), OGComplexDenseMatrix::create({{{-4.0,-11.0},{-2.0,-11.0},{-3.0,-11.0},{-4.0,-11.0}},{{-3.0,-11.0},{-4.0,-11.0},{-2.0,-11.0},{-3.0,-11.0}},{{-2.0,-11.0},{-3.0,-11.0},{-4.0,-11.0},{-2.0,-11.0}},{{-1.0,-11.0},{-2.0,-11.0},{-3.0,-11.0},{-4.0,-11.0}},{{0.0,-11.0},{-1.0,-11.0},{-2.0,-11.0},{-3.0,-11.0}}}), MATHSEQUAL),
// real 4x5 matrix minus complex scalar
new CheckBinary<MINUS>(OGRealDenseMatrix::create({{1.0,4.0,3.0,2.0,1.0},{2.0,1.0,4.0,3.0,2.0},{3.0,2.0,1.0,4.0,3.0},{4.0,3.0,2.0,1.0,4.0}}), OGComplexScalar::create({      5.0,     11.0}), OGComplexDenseMatrix::create({{{-4.0,-11.0},{-1.0,-11.0},{-2.0,-11.0},{-3.0,-11.0},{-4.0,-11.0}},{{-3.0,-11.0},{-4.0,-11.0},{-1.0,-11.0},{-2.0,-11.0},{-3.0,-11.0}},{{-2.0,-11.0},{-3.0,-11.0},{-4.0,-11.0},{-1.0,-11.0},{-2.0,-11.0}},{{-1.0,-11.0},{-2.0,-11.0},{-3.0,-11.0},{-4.0,-11.0},{-1.0,-11.0}}}), MATHSEQUAL),
// real scalar minus complex 5x4 matrix
new CheckBinary<MINUS>(OGRealScalar::create(      7.0), OGComplexDenseMatrix::create({{{1.0,5.0},{3.0,2.0},{2.0,3.0},{1.0,4.0}},{{2.0,4.0},{1.0,5.0},{3.0,2.0},{2.0,3.0}},{{3.0,3.0},{2.0,4.0},{1.0,5.0},{3.0,2.0}},{{4.0,2.0},{3.0,3.0},{2.0,4.0},{1.0,5.0}},{{5.0,1.0},{4.0,2.0},{3.0,3.0},{2.0,4.0}}}), OGComplexDenseMatrix::create({{{6.0,-5.0},{4.0,-2.0},{5.0,-3.0},{6.0,-4.0}},{{5.0,-4.0},{6.0,-5.0},{4.0,-2.0},{5.0,-3.0}},{{4.0,-3.0},{5.0,-4.0},{6.0,-5.0},{4.0,-2.0}},{{3.0,-2.0},{4.0,-3.0},{5.0,-4.0},{6.0,-5.0}},{{2.0,-1.0},{3.0,-2.0},{4.0,-3.0},{5.0,-4.0}}}), MATHSEQUAL),
// real scalar minus complex 4x5 matrix
new CheckBinary<MINUS>(OGRealScalar::create(      7.0), OGComplexDenseMatrix::create({{{1.0,4.0},{4.0,2.0},{3.0,3.0},{2.0,4.0},{1.0,5.0}},{{2.0,3.0},{1.0,4.0},{4.0,2.0},{3.0,3.0},{2.0,4.0}},{{3.0,2.0},{2.0,3.0},{1.0,4.0},{4.0,2.0},{3.0,3.0}},{{4.0,1.0},{3.0,2.0},{2.0,3.0},{1.0,4.0},{4.0,2.0}}}), OGComplexDenseMatrix::create({{{6.0,-4.0},{3.0,-2.0},{4.0,-3.0},{5.0,-4.0},{6.0,-5.0}},{{5.0,-3.0},{6.0,-4.0},{3.0,-2.0},{4.0,-3.0},{5.0,-4.0}},{{4.0,-2.0},{5.0,-3.0},{6.0,-4.0},{3.0,-2.0},{4.0,-3.0}},{{3.0,-1.0},{4.0,-2.0},{5.0,-3.0},{6.0,-4.0},{3.0,-2.0}}}), MATHSEQUAL),
// complex scalar minus complex 5x4 matrix
new CheckBinary<MINUS>(OGComplexScalar::create({      5.0,     11.0}), OGComplexDenseMatrix::create({{{1.0,5.0},{3.0,2.0},{2.0,3.0},{1.0,4.0}},{{2.0,4.0},{1.0,5.0},{3.0,2.0},{2.0,3.0}},{{3.0,3.0},{2.0,4.0},{1.0,5.0},{3.0,2.0}},{{4.0,2.0},{3.0,3.0},{2.0,4.0},{1.0,5.0}},{{5.0,1.0},{4.0,2.0},{3.0,3.0},{2.0,4.0}}}), OGComplexDenseMatrix::create({{{4.0,6.0},{2.0,9.0},{3.0,8.0},{4.0,7.0}},{{3.0,7.0},{4.0,6.0},{2.0,9.0},{3.0,8.0}},{{2.0,8.0},{3.0,7.0},{4.0,6.0},{2.0,9.0}},{{1.0,9.0},{2.0,8.0},{3.0,7.0},{4.0,6.0}},{{0.0,10.0},{1.0,9.0},{2.0,8.0},{3.0,7.0}}}), MATHSEQUAL),
// complex scalar minus complex 4x5 matrix
new CheckBinary<MINUS>(OGComplexScalar::create({      5.0,     11.0}), OGComplexDenseMatrix::create({{{1.0,4.0},{4.0,2.0},{3.0,3.0},{2.0,4.0},{1.0,5.0}},{{2.0,3.0},{1.0,4.0},{4.0,2.0},{3.0,3.0},{2.0,4.0}},{{3.0,2.0},{2.0,3.0},{1.0,4.0},{4.0,2.0},{3.0,3.0}},{{4.0,1.0},{3.0,2.0},{2.0,3.0},{1.0,4.0},{4.0,2.0}}}), OGComplexDenseMatrix::create({{{4.0,7.0},{1.0,9.0},{2.0,8.0},{3.0,7.0},{4.0,6.0}},{{3.0,8.0},{4.0,7.0},{1.0,9.0},{2.0,8.0},{3.0,7.0}},{{2.0,9.0},{3.0,8.0},{4.0,7.0},{1.0,9.0},{2.0,8.0}},{{1.0,10.0},{2.0,9.0},{3.0,8.0},{4.0,7.0},{1.0,9.0}}}), MATHSEQUAL),
// complex 5x4 matrix minus real scalar
new CheckBinary<MINUS>(OGComplexDenseMatrix::create({{{1.0,5.0},{3.0,2.0},{2.0,3.0},{1.0,4.0}},{{2.0,4.0},{1.0,5.0},{3.0,2.0},{2.0,3.0}},{{3.0,3.0},{2.0,4.0},{1.0,5.0},{3.0,2.0}},{{4.0,2.0},{3.0,3.0},{2.0,4.0},{1.0,5.0}},{{5.0,1.0},{4.0,2.0},{3.0,3.0},{2.0,4.0}}}), OGRealScalar::create(      7.0), OGComplexDenseMatrix::create({{{-6.0,5.0},{-4.0,2.0},{-5.0,3.0},{-6.0,4.0}},{{-5.0,4.0},{-6.0,5.0},{-4.0,2.0},{-5.0,3.0}},{{-4.0,3.0},{-5.0,4.0},{-6.0,5.0},{-4.0,2.0}},{{-3.0,2.0},{-4.0,3.0},{-5.0,4.0},{-6.0,5.0}},{{-2.0,1.0},{-3.0,2.0},{-4.0,3.0},{-5.0,4.0}}}), MATHSEQUAL),
// complex 4x5 matrix minus real scalar
new CheckBinary<MINUS>(OGComplexDenseMatrix::create({{{1.0,4.0},{4.0,2.0},{3.0,3.0},{2.0,4.0},{1.0,5.0}},{{2.0,3.0},{1.0,4.0},{4.0,2.0},{3.0,3.0},{2.0,4.0}},{{3.0,2.0},{2.0,3.0},{1.0,4.0},{4.0,2.0},{3.0,3.0}},{{4.0,1.0},{3.0,2.0},{2.0,3.0},{1.0,4.0},{4.0,2.0}}}), OGRealScalar::create(      7.0), OGComplexDenseMatrix::create({{{-6.0,4.0},{-3.0,2.0},{-4.0,3.0},{-5.0,4.0},{-6.0,5.0}},{{-5.0,3.0},{-6.0,4.0},{-3.0,2.0},{-4.0,3.0},{-5.0,4.0}},{{-4.0,2.0},{-5.0,3.0},{-6.0,4.0},{-3.0,2.0},{-4.0,3.0}},{{-3.0,1.0},{-4.0,2.0},{-5.0,3.0},{-6.0,4.0},{-3.0,2.0}}}), MATHSEQUAL),
// complex 5x4 matrix minus complex scalar
new CheckBinary<MINUS>(OGComplexDenseMatrix::create({{{1.0,5.0},{3.0,2.0},{2.0,3.0},{1.0,4.0}},{{2.0,4.0},{1.0,5.0},{3.0,2.0},{2.0,3.0}},{{3.0,3.0},{2.0,4.0},{1.0,5.0},{3.0,2.0}},{{4.0,2.0},{3.0,3.0},{2.0,4.0},{1.0,5.0}},{{5.0,1.0},{4.0,2.0},{3.0,3.0},{2.0,4.0}}}), OGComplexScalar::create({      5.0,     11.0}), OGComplexDenseMatrix::create({{{-4.0,-6.0},{-2.0,-9.0},{-3.0,-8.0},{-4.0,-7.0}},{{-3.0,-7.0},{-4.0,-6.0},{-2.0,-9.0},{-3.0,-8.0}},{{-2.0,-8.0},{-3.0,-7.0},{-4.0,-6.0},{-2.0,-9.0}},{{-1.0,-9.0},{-2.0,-8.0},{-3.0,-7.0},{-4.0,-6.0}},{{0.0,-10.0},{-1.0,-9.0},{-2.0,-8.0},{-3.0,-7.0}}}), MATHSEQUAL),
// complex 4x5 matrix minus complex scalar
new CheckBinary<MINUS>(OGComplexDenseMatrix::create({{{1.0,4.0},{4.0,2.0},{3.0,3.0},{2.0,4.0},{1.0,5.0}},{{2.0,3.0},{1.0,4.0},{4.0,2.0},{3.0,3.0},{2.0,4.0}},{{3.0,2.0},{2.0,3.0},{1.0,4.0},{4.0,2.0},{3.0,3.0}},{{4.0,1.0},{3.0,2.0},{2.0,3.0},{1.0,4.0},{4.0,2.0}}}), OGComplexScalar::create({      5.0,     11.0}), OGComplexDenseMatrix::create({{{-4.0,-7.0},{-1.0,-9.0},{-2.0,-8.0},{-3.0,-7.0},{-4.0,-6.0}},{{-3.0,-8.0},{-4.0,-7.0},{-1.0,-9.0},{-2.0,-8.0},{-3.0,-7.0}},{{-2.0,-9.0},{-3.0,-8.0},{-4.0,-7.0},{-1.0,-9.0},{-2.0,-8.0}},{{-1.0,-10.0},{-2.0,-9.0},{-3.0,-8.0},{-4.0,-7.0},{-1.0,-9.0}}}), MATHSEQUAL),
// real 5x4 matrix minus real 5x4 matrix
new CheckBinary<MINUS>(OGRealDenseMatrix::create({{1.0,3.0,2.0,1.0},{2.0,1.0,3.0,2.0},{3.0,2.0,1.0,3.0},{4.0,3.0,2.0,1.0},{5.0,4.0,3.0,2.0}}), OGRealDenseMatrix::create({{1.0,3.0,2.0,1.0},{2.0,1.0,3.0,2.0},{3.0,2.0,1.0,3.0},{4.0,3.0,2.0,1.0},{5.0,4.0,3.0,2.0}}), OGRealDenseMatrix::create({{0.0,0.0,0.0,0.0},{0.0,0.0,0.0,0.0},{0.0,0.0,0.0,0.0},{0.0,0.0,0.0,0.0},{0.0,0.0,0.0,0.0}}), MATHSEQUAL),
// real 4x5 matrix minus real 4x5 matrix
new CheckBinary<MINUS>(OGRealDenseMatrix::create({{1.0,4.0,3.0,2.0,1.0},{2.0,1.0,4.0,3.0,2.0},{3.0,2.0,1.0,4.0,3.0},{4.0,3.0,2.0,1.0,4.0}}), OGRealDenseMatrix::create({{1.0,4.0,3.0,2.0,1.0},{2.0,1.0,4.0,3.0,2.0},{3.0,2.0,1.0,4.0,3.0},{4.0,3.0,2.0,1.0,4.0}}), OGRealDenseMatrix::create({{0.0,0.0,0.0,0.0,0.0},{0.0,0.0,0.0,0.0,0.0},{0.0,0.0,0.0,0.0,0.0},{0.0,0.0,0.0,0.0,0.0}}), MATHSEQUAL),
// complex 5x4 matrix minus complex 5x4 matrix
new CheckBinary<MINUS>(OGComplexDenseMatrix::create({{{1.0,5.0},{3.0,2.0},{2.0,3.0},{1.0,4.0}},{{2.0,4.0},{1.0,5.0},{3.0,2.0},{2.0,3.0}},{{3.0,3.0},{2.0,4.0},{1.0,5.0},{3.0,2.0}},{{4.0,2.0},{3.0,3.0},{2.0,4.0},{1.0,5.0}},{{5.0,1.0},{4.0,2.0},{3.0,3.0},{2.0,4.0}}}), OGComplexDenseMatrix::create({{{1.0,5.0},{3.0,2.0},{2.0,3.0},{1.0,4.0}},{{2.0,4.0},{1.0,5.0},{3.0,2.0},{2.0,3.0}},{{3.0,3.0},{2.0,4.0},{1.0,5.0},{3.0,2.0}},{{4.0,2.0},{3.0,3.0},{2.0,4.0},{1.0,5.0}},{{5.0,1.0},{4.0,2.0},{3.0,3.0},{2.0,4.0}}}), OGRealDenseMatrix::create({{0.0,0.0,0.0,0.0},{0.0,0.0,0.0,0.0},{0.0,0.0,0.0,0.0},{0.0,0.0,0.0,0.0},{0.0,0.0,0.0,0.0}}), MATHSEQUAL),
// complex 4x5 matrix minus complex 4x5 matrix
new CheckBinary<MINUS>(OGComplexDenseMatrix::create({{{1.0,4.0},{4.0,2.0},{3.0,3.0},{2.0,4.0},{1.0,5.0}},{{2.0,3.0},{1.0,4.0},{4.0,2.0},{3.0,3.0},{2.0,4.0}},{{3.0,2.0},{2.0,3.0},{1.0,4.0},{4.0,2.0},{3.0,3.0}},{{4.0,1.0},{3.0,2.0},{2.0,3.0},{1.0,4.0},{4.0,2.0}}}), OGComplexDenseMatrix::create({{{1.0,4.0},{4.0,2.0},{3.0,3.0},{2.0,4.0},{1.0,5.0}},{{2.0,3.0},{1.0,4.0},{4.0,2.0},{3.0,3.0},{2.0,4.0}},{{3.0,2.0},{2.0,3.0},{1.0,4.0},{4.0,2.0},{3.0,3.0}},{{4.0,1.0},{3.0,2.0},{2.0,3.0},{1.0,4.0},{4.0,2.0}}}), OGRealDenseMatrix::create({{0.0,0.0,0.0,0.0,0.0},{0.0,0.0,0.0,0.0,0.0},{0.0,0.0,0.0,0.0,0.0},{0.0,0.0,0.0,0.0,0.0}}), MATHSEQUAL)

     )
   ); 
   
