/**
 * Copyright (C) 2014 - present by OpenGamma Inc. and the OpenGamma group of companies
 *
 * Please see distribution for license.
 */
  // NOTE: This code is autogenerated, see src/generator/scripts/testgen.m
  
 #include "gtest/gtest.h"
 #include "terminal.hh"
 #include "execution.hh"
 #include "dispatch.hh"
 #include "testnodes.hh"
 
 using namespace std;
 using namespace librdag;
 using namespace testnodes;
 using ::testing::TestWithParam;
 using ::testing::Values;
 
   /*
    * Check TIMES node behaves
    */
 
   BINARY_NODE_TEST_SETUP(TIMES)
 
   INSTANTIATE_NODE_TEST_CASE_P(TIMESTests,TIMES,
     Values
     (
       // real scalar times real scalar
new CheckBinary<TIMES>(OGRealScalar::create(      7.0), OGRealScalar::create(      7.0), OGRealScalar::create(     49.0), MATHSEQUAL),
// real scalar times complex scalar
new CheckBinary<TIMES>(OGRealScalar::create(      7.0), OGComplexScalar::create({      5.0,     11.0}), OGComplexScalar::create({     35.0,     77.0}), MATHSEQUAL),
// complex scalar times real scalar
new CheckBinary<TIMES>(OGComplexScalar::create({      5.0,     11.0}), OGRealScalar::create(      7.0), OGComplexScalar::create({     35.0,     77.0}), MATHSEQUAL),
// complex scalar times complex scalar
new CheckBinary<TIMES>(OGComplexScalar::create({      5.0,     11.0}), OGComplexScalar::create({      5.0,     11.0}), OGComplexScalar::create({    -96.0,    110.0}), MATHSEQUAL),
// real scalar times real length 4 column vector
new CheckBinary<TIMES>(OGRealScalar::create(      7.0), OGRealDenseMatrix::create({{1.0},{2.0},{3.0},{4.0}}), OGRealDenseMatrix::create({{7.0},{14.0},{21.0},{28.0}}), MATHSEQUAL),
// real scalar times real length 4 row vector
new CheckBinary<TIMES>(OGRealScalar::create(      7.0), OGRealDenseMatrix::create({{4.0,3.0,2.0,1.0}}), OGRealDenseMatrix::create({{28.0,21.0,14.0,7.0}}), MATHSEQUAL),
// complex scalar times real length 4 column vector
new CheckBinary<TIMES>(OGComplexScalar::create({      5.0,     11.0}), OGRealDenseMatrix::create({{1.0},{2.0},{3.0},{4.0}}), OGComplexDenseMatrix::create({{{5.0,11.0}},{{10.0,22.0}},{{15.0,33.0}},{{20.0,44.0}}}), MATHSEQUAL),
// complex scalar times real length 4 row vector
new CheckBinary<TIMES>(OGComplexScalar::create({      5.0,     11.0}), OGRealDenseMatrix::create({{4.0,3.0,2.0,1.0}}), OGComplexDenseMatrix::create({{{20.0,44.0},{15.0,33.0},{10.0,22.0},{5.0,11.0}}}), MATHSEQUAL),
// real length 4 column vector times real scalar
new CheckBinary<TIMES>(OGRealDenseMatrix::create({{1.0},{2.0},{3.0},{4.0}}), OGRealScalar::create(      7.0), OGRealDenseMatrix::create({{7.0},{14.0},{21.0},{28.0}}), MATHSEQUAL),
// real length 4 row vector times real scalar
new CheckBinary<TIMES>(OGRealDenseMatrix::create({{4.0,3.0,2.0,1.0}}), OGRealScalar::create(      7.0), OGRealDenseMatrix::create({{28.0,21.0,14.0,7.0}}), MATHSEQUAL),
// real length 4 column vector times complex scalar
new CheckBinary<TIMES>(OGRealDenseMatrix::create({{1.0},{2.0},{3.0},{4.0}}), OGComplexScalar::create({      5.0,     11.0}), OGComplexDenseMatrix::create({{{5.0,11.0}},{{10.0,22.0}},{{15.0,33.0}},{{20.0,44.0}}}), MATHSEQUAL),
// real length 4 row vector times complex scalar
new CheckBinary<TIMES>(OGRealDenseMatrix::create({{4.0,3.0,2.0,1.0}}), OGComplexScalar::create({      5.0,     11.0}), OGComplexDenseMatrix::create({{{20.0,44.0},{15.0,33.0},{10.0,22.0},{5.0,11.0}}}), MATHSEQUAL),
// real scalar times complex length 4 column vector
new CheckBinary<TIMES>(OGRealScalar::create(      7.0), OGComplexDenseMatrix::create({{{1.0,4.0}},{{2.0,3.0}},{{3.0,2.0}},{{4.0,1.0}}}), OGComplexDenseMatrix::create({{{7.0,28.0}},{{14.0,21.0}},{{21.0,14.0}},{{28.0,7.0}}}), MATHSEQUAL),
// real scalar times complex length 4 row vector
new CheckBinary<TIMES>(OGRealScalar::create(      7.0), OGComplexDenseMatrix::create({{{4.0,1.0},{3.0,2.0},{2.0,3.0},{1.0,4.0}}}), OGComplexDenseMatrix::create({{{28.0,7.0},{21.0,14.0},{14.0,21.0},{7.0,28.0}}}), MATHSEQUAL),
// complex scalar times complex length 4 column vector
new CheckBinary<TIMES>(OGComplexScalar::create({      5.0,     11.0}), OGComplexDenseMatrix::create({{{1.0,4.0}},{{2.0,3.0}},{{3.0,2.0}},{{4.0,1.0}}}), OGComplexDenseMatrix::create({{{-39.0,31.0}},{{-23.0,37.0}},{{-7.0,43.0}},{{9.0,49.0}}}), MATHSEQUAL),
// complex scalar times complex length 4 row vector
new CheckBinary<TIMES>(OGComplexScalar::create({      5.0,     11.0}), OGComplexDenseMatrix::create({{{4.0,1.0},{3.0,2.0},{2.0,3.0},{1.0,4.0}}}), OGComplexDenseMatrix::create({{{9.0,49.0},{-7.0,43.0},{-23.0,37.0},{-39.0,31.0}}}), MATHSEQUAL),
// complex length 4 column vector times real scalar
new CheckBinary<TIMES>(OGComplexDenseMatrix::create({{{1.0,4.0}},{{2.0,3.0}},{{3.0,2.0}},{{4.0,1.0}}}), OGRealScalar::create(      7.0), OGComplexDenseMatrix::create({{{7.0,28.0}},{{14.0,21.0}},{{21.0,14.0}},{{28.0,7.0}}}), MATHSEQUAL),
// complex length 4 row vector times real scalar
new CheckBinary<TIMES>(OGComplexDenseMatrix::create({{{4.0,1.0},{3.0,2.0},{2.0,3.0},{1.0,4.0}}}), OGRealScalar::create(      7.0), OGComplexDenseMatrix::create({{{28.0,7.0},{21.0,14.0},{14.0,21.0},{7.0,28.0}}}), MATHSEQUAL),
// complex length 4 column vector times complex scalar
new CheckBinary<TIMES>(OGComplexDenseMatrix::create({{{1.0,4.0}},{{2.0,3.0}},{{3.0,2.0}},{{4.0,1.0}}}), OGComplexScalar::create({      5.0,     11.0}), OGComplexDenseMatrix::create({{{-39.0,31.0}},{{-23.0,37.0}},{{-7.0,43.0}},{{9.0,49.0}}}), MATHSEQUAL),
// complex length 4 row vector times complex scalar
new CheckBinary<TIMES>(OGComplexDenseMatrix::create({{{4.0,1.0},{3.0,2.0},{2.0,3.0},{1.0,4.0}}}), OGComplexScalar::create({      5.0,     11.0}), OGComplexDenseMatrix::create({{{9.0,49.0},{-7.0,43.0},{-23.0,37.0},{-39.0,31.0}}}), MATHSEQUAL),
// real scalar times real 5x4 matrix
new CheckBinary<TIMES>(OGRealScalar::create(      7.0), OGRealDenseMatrix::create({{1.0,3.0,2.0,1.0},{2.0,1.0,3.0,2.0},{3.0,2.0,1.0,3.0},{4.0,3.0,2.0,1.0},{5.0,4.0,3.0,2.0}}), OGRealDenseMatrix::create({{7.0,21.0,14.0,7.0},{14.0,7.0,21.0,14.0},{21.0,14.0,7.0,21.0},{28.0,21.0,14.0,7.0},{35.0,28.0,21.0,14.0}}), MATHSEQUAL),
// real scalar times real 4x5 matrix
new CheckBinary<TIMES>(OGRealScalar::create(      7.0), OGRealDenseMatrix::create({{1.0,4.0,3.0,2.0,1.0},{2.0,1.0,4.0,3.0,2.0},{3.0,2.0,1.0,4.0,3.0},{4.0,3.0,2.0,1.0,4.0}}), OGRealDenseMatrix::create({{7.0,28.0,21.0,14.0,7.0},{14.0,7.0,28.0,21.0,14.0},{21.0,14.0,7.0,28.0,21.0},{28.0,21.0,14.0,7.0,28.0}}), MATHSEQUAL),
// complex scalar times real 5x4 matrix
new CheckBinary<TIMES>(OGComplexScalar::create({      5.0,     11.0}), OGRealDenseMatrix::create({{1.0,3.0,2.0,1.0},{2.0,1.0,3.0,2.0},{3.0,2.0,1.0,3.0},{4.0,3.0,2.0,1.0},{5.0,4.0,3.0,2.0}}), OGComplexDenseMatrix::create({{{5.0,11.0},{15.0,33.0},{10.0,22.0},{5.0,11.0}},{{10.0,22.0},{5.0,11.0},{15.0,33.0},{10.0,22.0}},{{15.0,33.0},{10.0,22.0},{5.0,11.0},{15.0,33.0}},{{20.0,44.0},{15.0,33.0},{10.0,22.0},{5.0,11.0}},{{25.0,55.0},{20.0,44.0},{15.0,33.0},{10.0,22.0}}}), MATHSEQUAL),
// complex scalar times real 4x5 matrix
new CheckBinary<TIMES>(OGComplexScalar::create({      5.0,     11.0}), OGRealDenseMatrix::create({{1.0,4.0,3.0,2.0,1.0},{2.0,1.0,4.0,3.0,2.0},{3.0,2.0,1.0,4.0,3.0},{4.0,3.0,2.0,1.0,4.0}}), OGComplexDenseMatrix::create({{{5.0,11.0},{20.0,44.0},{15.0,33.0},{10.0,22.0},{5.0,11.0}},{{10.0,22.0},{5.0,11.0},{20.0,44.0},{15.0,33.0},{10.0,22.0}},{{15.0,33.0},{10.0,22.0},{5.0,11.0},{20.0,44.0},{15.0,33.0}},{{20.0,44.0},{15.0,33.0},{10.0,22.0},{5.0,11.0},{20.0,44.0}}}), MATHSEQUAL),
// real 5x4 matrix times real scalar
new CheckBinary<TIMES>(OGRealDenseMatrix::create({{1.0,3.0,2.0,1.0},{2.0,1.0,3.0,2.0},{3.0,2.0,1.0,3.0},{4.0,3.0,2.0,1.0},{5.0,4.0,3.0,2.0}}), OGRealScalar::create(      7.0), OGRealDenseMatrix::create({{7.0,21.0,14.0,7.0},{14.0,7.0,21.0,14.0},{21.0,14.0,7.0,21.0},{28.0,21.0,14.0,7.0},{35.0,28.0,21.0,14.0}}), MATHSEQUAL),
// real 4x5 matrix times real scalar
new CheckBinary<TIMES>(OGRealDenseMatrix::create({{1.0,4.0,3.0,2.0,1.0},{2.0,1.0,4.0,3.0,2.0},{3.0,2.0,1.0,4.0,3.0},{4.0,3.0,2.0,1.0,4.0}}), OGRealScalar::create(      7.0), OGRealDenseMatrix::create({{7.0,28.0,21.0,14.0,7.0},{14.0,7.0,28.0,21.0,14.0},{21.0,14.0,7.0,28.0,21.0},{28.0,21.0,14.0,7.0,28.0}}), MATHSEQUAL),
// real 5x4 matrix times complex scalar
new CheckBinary<TIMES>(OGRealDenseMatrix::create({{1.0,3.0,2.0,1.0},{2.0,1.0,3.0,2.0},{3.0,2.0,1.0,3.0},{4.0,3.0,2.0,1.0},{5.0,4.0,3.0,2.0}}), OGComplexScalar::create({      5.0,     11.0}), OGComplexDenseMatrix::create({{{5.0,11.0},{15.0,33.0},{10.0,22.0},{5.0,11.0}},{{10.0,22.0},{5.0,11.0},{15.0,33.0},{10.0,22.0}},{{15.0,33.0},{10.0,22.0},{5.0,11.0},{15.0,33.0}},{{20.0,44.0},{15.0,33.0},{10.0,22.0},{5.0,11.0}},{{25.0,55.0},{20.0,44.0},{15.0,33.0},{10.0,22.0}}}), MATHSEQUAL),
// real 4x5 matrix times complex scalar
new CheckBinary<TIMES>(OGRealDenseMatrix::create({{1.0,4.0,3.0,2.0,1.0},{2.0,1.0,4.0,3.0,2.0},{3.0,2.0,1.0,4.0,3.0},{4.0,3.0,2.0,1.0,4.0}}), OGComplexScalar::create({      5.0,     11.0}), OGComplexDenseMatrix::create({{{5.0,11.0},{20.0,44.0},{15.0,33.0},{10.0,22.0},{5.0,11.0}},{{10.0,22.0},{5.0,11.0},{20.0,44.0},{15.0,33.0},{10.0,22.0}},{{15.0,33.0},{10.0,22.0},{5.0,11.0},{20.0,44.0},{15.0,33.0}},{{20.0,44.0},{15.0,33.0},{10.0,22.0},{5.0,11.0},{20.0,44.0}}}), MATHSEQUAL),
// real scalar times complex 5x4 matrix
new CheckBinary<TIMES>(OGRealScalar::create(      7.0), OGComplexDenseMatrix::create({{{1.0,5.0},{3.0,2.0},{2.0,3.0},{1.0,4.0}},{{2.0,4.0},{1.0,5.0},{3.0,2.0},{2.0,3.0}},{{3.0,3.0},{2.0,4.0},{1.0,5.0},{3.0,2.0}},{{4.0,2.0},{3.0,3.0},{2.0,4.0},{1.0,5.0}},{{5.0,1.0},{4.0,2.0},{3.0,3.0},{2.0,4.0}}}), OGComplexDenseMatrix::create({{{7.0,35.0},{21.0,14.0},{14.0,21.0},{7.0,28.0}},{{14.0,28.0},{7.0,35.0},{21.0,14.0},{14.0,21.0}},{{21.0,21.0},{14.0,28.0},{7.0,35.0},{21.0,14.0}},{{28.0,14.0},{21.0,21.0},{14.0,28.0},{7.0,35.0}},{{35.0,7.0},{28.0,14.0},{21.0,21.0},{14.0,28.0}}}), MATHSEQUAL),
// real scalar times complex 4x5 matrix
new CheckBinary<TIMES>(OGRealScalar::create(      7.0), OGComplexDenseMatrix::create({{{1.0,4.0},{4.0,2.0},{3.0,3.0},{2.0,4.0},{1.0,5.0}},{{2.0,3.0},{1.0,4.0},{4.0,2.0},{3.0,3.0},{2.0,4.0}},{{3.0,2.0},{2.0,3.0},{1.0,4.0},{4.0,2.0},{3.0,3.0}},{{4.0,1.0},{3.0,2.0},{2.0,3.0},{1.0,4.0},{4.0,2.0}}}), OGComplexDenseMatrix::create({{{7.0,28.0},{28.0,14.0},{21.0,21.0},{14.0,28.0},{7.0,35.0}},{{14.0,21.0},{7.0,28.0},{28.0,14.0},{21.0,21.0},{14.0,28.0}},{{21.0,14.0},{14.0,21.0},{7.0,28.0},{28.0,14.0},{21.0,21.0}},{{28.0,7.0},{21.0,14.0},{14.0,21.0},{7.0,28.0},{28.0,14.0}}}), MATHSEQUAL),
// complex scalar times complex 5x4 matrix
new CheckBinary<TIMES>(OGComplexScalar::create({      5.0,     11.0}), OGComplexDenseMatrix::create({{{1.0,5.0},{3.0,2.0},{2.0,3.0},{1.0,4.0}},{{2.0,4.0},{1.0,5.0},{3.0,2.0},{2.0,3.0}},{{3.0,3.0},{2.0,4.0},{1.0,5.0},{3.0,2.0}},{{4.0,2.0},{3.0,3.0},{2.0,4.0},{1.0,5.0}},{{5.0,1.0},{4.0,2.0},{3.0,3.0},{2.0,4.0}}}), OGComplexDenseMatrix::create({{{-50.0,36.0},{-7.0,43.0},{-23.0,37.0},{-39.0,31.0}},{{-34.0,42.0},{-50.0,36.0},{-7.0,43.0},{-23.0,37.0}},{{-18.0,48.0},{-34.0,42.0},{-50.0,36.0},{-7.0,43.0}},{{-2.0,54.0},{-18.0,48.0},{-34.0,42.0},{-50.0,36.0}},{{14.0,60.0},{-2.0,54.0},{-18.0,48.0},{-34.0,42.0}}}), MATHSEQUAL),
// complex scalar times complex 4x5 matrix
new CheckBinary<TIMES>(OGComplexScalar::create({      5.0,     11.0}), OGComplexDenseMatrix::create({{{1.0,4.0},{4.0,2.0},{3.0,3.0},{2.0,4.0},{1.0,5.0}},{{2.0,3.0},{1.0,4.0},{4.0,2.0},{3.0,3.0},{2.0,4.0}},{{3.0,2.0},{2.0,3.0},{1.0,4.0},{4.0,2.0},{3.0,3.0}},{{4.0,1.0},{3.0,2.0},{2.0,3.0},{1.0,4.0},{4.0,2.0}}}), OGComplexDenseMatrix::create({{{-39.0,31.0},{-2.0,54.0},{-18.0,48.0},{-34.0,42.0},{-50.0,36.0}},{{-23.0,37.0},{-39.0,31.0},{-2.0,54.0},{-18.0,48.0},{-34.0,42.0}},{{-7.0,43.0},{-23.0,37.0},{-39.0,31.0},{-2.0,54.0},{-18.0,48.0}},{{9.0,49.0},{-7.0,43.0},{-23.0,37.0},{-39.0,31.0},{-2.0,54.0}}}), MATHSEQUAL),
// complex 5x4 matrix times real scalar
new CheckBinary<TIMES>(OGComplexDenseMatrix::create({{{1.0,5.0},{3.0,2.0},{2.0,3.0},{1.0,4.0}},{{2.0,4.0},{1.0,5.0},{3.0,2.0},{2.0,3.0}},{{3.0,3.0},{2.0,4.0},{1.0,5.0},{3.0,2.0}},{{4.0,2.0},{3.0,3.0},{2.0,4.0},{1.0,5.0}},{{5.0,1.0},{4.0,2.0},{3.0,3.0},{2.0,4.0}}}), OGRealScalar::create(      7.0), OGComplexDenseMatrix::create({{{7.0,35.0},{21.0,14.0},{14.0,21.0},{7.0,28.0}},{{14.0,28.0},{7.0,35.0},{21.0,14.0},{14.0,21.0}},{{21.0,21.0},{14.0,28.0},{7.0,35.0},{21.0,14.0}},{{28.0,14.0},{21.0,21.0},{14.0,28.0},{7.0,35.0}},{{35.0,7.0},{28.0,14.0},{21.0,21.0},{14.0,28.0}}}), MATHSEQUAL),
// complex 4x5 matrix times real scalar
new CheckBinary<TIMES>(OGComplexDenseMatrix::create({{{1.0,4.0},{4.0,2.0},{3.0,3.0},{2.0,4.0},{1.0,5.0}},{{2.0,3.0},{1.0,4.0},{4.0,2.0},{3.0,3.0},{2.0,4.0}},{{3.0,2.0},{2.0,3.0},{1.0,4.0},{4.0,2.0},{3.0,3.0}},{{4.0,1.0},{3.0,2.0},{2.0,3.0},{1.0,4.0},{4.0,2.0}}}), OGRealScalar::create(      7.0), OGComplexDenseMatrix::create({{{7.0,28.0},{28.0,14.0},{21.0,21.0},{14.0,28.0},{7.0,35.0}},{{14.0,21.0},{7.0,28.0},{28.0,14.0},{21.0,21.0},{14.0,28.0}},{{21.0,14.0},{14.0,21.0},{7.0,28.0},{28.0,14.0},{21.0,21.0}},{{28.0,7.0},{21.0,14.0},{14.0,21.0},{7.0,28.0},{28.0,14.0}}}), MATHSEQUAL),
// complex 5x4 matrix times complex scalar
new CheckBinary<TIMES>(OGComplexDenseMatrix::create({{{1.0,5.0},{3.0,2.0},{2.0,3.0},{1.0,4.0}},{{2.0,4.0},{1.0,5.0},{3.0,2.0},{2.0,3.0}},{{3.0,3.0},{2.0,4.0},{1.0,5.0},{3.0,2.0}},{{4.0,2.0},{3.0,3.0},{2.0,4.0},{1.0,5.0}},{{5.0,1.0},{4.0,2.0},{3.0,3.0},{2.0,4.0}}}), OGComplexScalar::create({      5.0,     11.0}), OGComplexDenseMatrix::create({{{-50.0,36.0},{-7.0,43.0},{-23.0,37.0},{-39.0,31.0}},{{-34.0,42.0},{-50.0,36.0},{-7.0,43.0},{-23.0,37.0}},{{-18.0,48.0},{-34.0,42.0},{-50.0,36.0},{-7.0,43.0}},{{-2.0,54.0},{-18.0,48.0},{-34.0,42.0},{-50.0,36.0}},{{14.0,60.0},{-2.0,54.0},{-18.0,48.0},{-34.0,42.0}}}), MATHSEQUAL),
// complex 4x5 matrix times complex scalar
new CheckBinary<TIMES>(OGComplexDenseMatrix::create({{{1.0,4.0},{4.0,2.0},{3.0,3.0},{2.0,4.0},{1.0,5.0}},{{2.0,3.0},{1.0,4.0},{4.0,2.0},{3.0,3.0},{2.0,4.0}},{{3.0,2.0},{2.0,3.0},{1.0,4.0},{4.0,2.0},{3.0,3.0}},{{4.0,1.0},{3.0,2.0},{2.0,3.0},{1.0,4.0},{4.0,2.0}}}), OGComplexScalar::create({      5.0,     11.0}), OGComplexDenseMatrix::create({{{-39.0,31.0},{-2.0,54.0},{-18.0,48.0},{-34.0,42.0},{-50.0,36.0}},{{-23.0,37.0},{-39.0,31.0},{-2.0,54.0},{-18.0,48.0},{-34.0,42.0}},{{-7.0,43.0},{-23.0,37.0},{-39.0,31.0},{-2.0,54.0},{-18.0,48.0}},{{9.0,49.0},{-7.0,43.0},{-23.0,37.0},{-39.0,31.0},{-2.0,54.0}}}), MATHSEQUAL),
// real 5x4 matrix times real 5x4 matrix
new CheckBinary<TIMES>(OGRealDenseMatrix::create({{1.0,3.0,2.0,1.0},{2.0,1.0,3.0,2.0},{3.0,2.0,1.0,3.0},{4.0,3.0,2.0,1.0},{5.0,4.0,3.0,2.0}}), OGRealDenseMatrix::create({{1.0,3.0,2.0,1.0},{2.0,1.0,3.0,2.0},{3.0,2.0,1.0,3.0},{4.0,3.0,2.0,1.0},{5.0,4.0,3.0,2.0}}), OGRealDenseMatrix::create({{1.0,9.0,4.0,1.0},{4.0,1.0,9.0,4.0},{9.0,4.0,1.0,9.0},{16.0,9.0,4.0,1.0},{25.0,16.0,9.0,4.0}}), MATHSEQUAL),
// real 4x5 matrix times real 4x5 matrix
new CheckBinary<TIMES>(OGRealDenseMatrix::create({{1.0,4.0,3.0,2.0,1.0},{2.0,1.0,4.0,3.0,2.0},{3.0,2.0,1.0,4.0,3.0},{4.0,3.0,2.0,1.0,4.0}}), OGRealDenseMatrix::create({{1.0,4.0,3.0,2.0,1.0},{2.0,1.0,4.0,3.0,2.0},{3.0,2.0,1.0,4.0,3.0},{4.0,3.0,2.0,1.0,4.0}}), OGRealDenseMatrix::create({{1.0,16.0,9.0,4.0,1.0},{4.0,1.0,16.0,9.0,4.0},{9.0,4.0,1.0,16.0,9.0},{16.0,9.0,4.0,1.0,16.0}}), MATHSEQUAL),
// complex 5x4 matrix times complex 5x4 matrix
new CheckBinary<TIMES>(OGComplexDenseMatrix::create({{{1.0,5.0},{3.0,2.0},{2.0,3.0},{1.0,4.0}},{{2.0,4.0},{1.0,5.0},{3.0,2.0},{2.0,3.0}},{{3.0,3.0},{2.0,4.0},{1.0,5.0},{3.0,2.0}},{{4.0,2.0},{3.0,3.0},{2.0,4.0},{1.0,5.0}},{{5.0,1.0},{4.0,2.0},{3.0,3.0},{2.0,4.0}}}), OGComplexDenseMatrix::create({{{1.0,5.0},{3.0,2.0},{2.0,3.0},{1.0,4.0}},{{2.0,4.0},{1.0,5.0},{3.0,2.0},{2.0,3.0}},{{3.0,3.0},{2.0,4.0},{1.0,5.0},{3.0,2.0}},{{4.0,2.0},{3.0,3.0},{2.0,4.0},{1.0,5.0}},{{5.0,1.0},{4.0,2.0},{3.0,3.0},{2.0,4.0}}}), OGComplexDenseMatrix::create({{{-24.0,10.0},{5.0,12.0},{-5.0,12.0},{-15.0,8.0}},{{-12.0,16.0},{-24.0,10.0},{5.0,12.0},{-5.0,12.0}},{{0.0,18.0},{-12.0,16.0},{-24.0,10.0},{5.0,12.0}},{{12.0,16.0},{0.0,18.0},{-12.0,16.0},{-24.0,10.0}},{{24.0,10.0},{12.0,16.0},{0.0,18.0},{-12.0,16.0}}}), MATHSEQUAL),
// complex 4x5 matrix times complex 4x5 matrix
new CheckBinary<TIMES>(OGComplexDenseMatrix::create({{{1.0,4.0},{4.0,2.0},{3.0,3.0},{2.0,4.0},{1.0,5.0}},{{2.0,3.0},{1.0,4.0},{4.0,2.0},{3.0,3.0},{2.0,4.0}},{{3.0,2.0},{2.0,3.0},{1.0,4.0},{4.0,2.0},{3.0,3.0}},{{4.0,1.0},{3.0,2.0},{2.0,3.0},{1.0,4.0},{4.0,2.0}}}), OGComplexDenseMatrix::create({{{1.0,4.0},{4.0,2.0},{3.0,3.0},{2.0,4.0},{1.0,5.0}},{{2.0,3.0},{1.0,4.0},{4.0,2.0},{3.0,3.0},{2.0,4.0}},{{3.0,2.0},{2.0,3.0},{1.0,4.0},{4.0,2.0},{3.0,3.0}},{{4.0,1.0},{3.0,2.0},{2.0,3.0},{1.0,4.0},{4.0,2.0}}}), OGComplexDenseMatrix::create({{{-15.0,8.0},{12.0,16.0},{0.0,18.0},{-12.0,16.0},{-24.0,10.0}},{{-5.0,12.0},{-15.0,8.0},{12.0,16.0},{0.0,18.0},{-12.0,16.0}},{{5.0,12.0},{-5.0,12.0},{-15.0,8.0},{12.0,16.0},{0.0,18.0}},{{15.0,8.0},{5.0,12.0},{-5.0,12.0},{-15.0,8.0},{12.0,16.0}}}), MATHSEQUAL)

     )
   ); 
   
