/**
 * Copyright (C) 2013 - present by OpenGamma Inc. and the OpenGamma group of companies
 *
 * Please see distribution for license.
 */

#include <iostream>
#include "expressionbase.hh"
#include "expression.hh"
#include "terminal.hh"
#include "exceptions.hh"

using namespace std;

namespace librdag
{

/*
 * OGExpr
 */

OGExpr::OGExpr()
{
  // _regs are safe to immediately own their contents because we don't put anything
  // in them during construction.
  _regs.set_ownership(true);
}

OGExpr::~OGExpr() {}

const ArgContainer&
OGExpr::getArgs() const
{
  return _args;
}

size_t
OGExpr::getNArgs() const
{
  return _args.size();
}

void
OGExpr::accept(Visitor& v) const
{
  v.visit(this);
}

const OGExpr*
OGExpr::asOGExpr() const
{
  return this;
}

RegContainer&
OGExpr::getRegs() const
{
  return _regs;
}

void OGExpr::debug_print() const
{
  cout << "OGExpr::debug_print()" << std::endl;
}


/**
 * Things that extend OGExpr
 */

OGUnaryExpr::OGUnaryExpr(const OGNumeric* arg): OGExpr{}
{
  if (arg == nullptr)
  {
    throw rdag_error("Null operand passed to unary expression");
  }
  _args.push_back(arg);
  // We got all the way through building the OGUnaryExpr object, so it
  // is now safe to own the arguments.
  _args.set_ownership(true);
}

OGBinaryExpr::OGBinaryExpr(const OGNumeric* arg0, const OGNumeric* arg1): OGExpr{}
{
  if (arg0 == nullptr)
  {
    throw rdag_error("Null operand passed to binary expression in arg0");
  }
  if (arg1 == nullptr)
  {
    throw rdag_error("Null operand passed to binary expression in arg1");
  }
  _args.push_back(arg0);
  _args.push_back(arg1);
  // We got all the way through building the OGBinaryExpr object, so it
  // is now safe to own the arguments.
  _args.set_ownership(true);
}

/**
 * Non autogenerated nodes
 */

/**
 * COPY node
 */

COPY::COPY(const OGNumeric* arg): OGUnaryExpr{arg} {}

OGNumeric*
COPY::copy() const
{
  return new COPY(_args[0]->copy());
}

const COPY*
COPY::asCOPY() const
{
  return this;
}

void
COPY::debug_print() const
{
        cout << "COPY base class" << endl;
}

ExprType_t
COPY::getType() const
{
  return COPY_ENUM;
}

/**
 * SELECTRESULT node
 */
SELECTRESULT::SELECTRESULT(const OGNumeric* arg0, const OGNumeric* arg1): OGExpr{}
{
  if (arg0 == nullptr)
  {
    throw rdag_error("Null operand passed to binary expression in arg0");
  }
  if (arg1 == nullptr)
  {
    throw rdag_error("Null operand passed to binary expression in arg1");
  }
  if (arg1->getType() != INTEGER_SCALAR_ENUM)
  {
    throw rdag_error("Second argument of SelectResult is not an integer");
  }
  _args.push_back(arg0);
  _args.push_back(arg1);
  // We got all the way through building the SELECTRESULT object, so it
  // is now safe to own the arguments.
  _args.set_ownership(true);
}

OGNumeric*
SELECTRESULT::copy() const
{
  return new SELECTRESULT(_args[0]->copy(), _args[1]->copy());
}

const SELECTRESULT*
SELECTRESULT::asSELECTRESULT() const
{
  return this;
}

void
SELECTRESULT::debug_print() const
{
        printf("SELECTRESULT base class\n");
}

ExprType_t
SELECTRESULT::getType() const
{
  return SELECTRESULT_ENUM;
}


/**
 * NORM2 node
 */

NORM2::NORM2(const OGNumeric* arg): OGUnaryExpr{arg} {}

OGNumeric*
NORM2::copy() const
{

  return new NORM2(_args[0]->copy());
}

const NORM2*
NORM2::asNORM2() const
{
  return this;
}

void
NORM2::debug_print() const
{
        cout << "NORM2 base class" << endl;
}

ExprType_t
NORM2::getType() const
{
  return NORM2_ENUM;
}

/**
 * PINV node
 */

PINV::PINV(const OGNumeric* arg): OGUnaryExpr{arg} {}

OGNumeric*
PINV::copy() const
{

  return new PINV(_args[0]->copy());
}

const PINV*
PINV::asPINV() const
{
  return this;
}

void
PINV::debug_print() const
{
        cout << "PINV base class" << endl;
}

ExprType_t
PINV::getType() const
{
  return PINV_ENUM;
}


/**
 * TRANSPOSE node
 */

TRANSPOSE::TRANSPOSE(const OGNumeric* arg): OGUnaryExpr{arg} {}

OGNumeric*
TRANSPOSE::copy() const
{

  return new TRANSPOSE(_args[0]->copy());
}

const TRANSPOSE*
TRANSPOSE::asTRANSPOSE() const
{
  return this;
}

void
TRANSPOSE::debug_print() const
{
        cout << "TRANSPOSE base class" << endl;
}

ExprType_t
TRANSPOSE::getType() const
{
  return TRANSPOSE_ENUM;
}


/**
 * CTRANSPOSE node
 */

CTRANSPOSE::CTRANSPOSE(const OGNumeric* arg): OGUnaryExpr{arg} {}

OGNumeric*
CTRANSPOSE::copy() const
{

  return new CTRANSPOSE(_args[0]->copy());
}

const CTRANSPOSE*
CTRANSPOSE::asCTRANSPOSE() const
{
  return this;
}

void
CTRANSPOSE::debug_print() const
{
        cout << "CTRANSPOSE base class" << endl;
}

ExprType_t
CTRANSPOSE::getType() const
{
  return CTRANSPOSE_ENUM;
}

/**
 * SVD node
 */

SVD::SVD(const OGNumeric* arg): OGUnaryExpr{arg} {}

OGNumeric*
SVD::copy() const
{
  return new SVD(_args[0]->copy());
}

const SVD*
SVD::asSVD() const
{
  return this;
}

void
SVD::debug_print() const
{
  cout << "SVD node" << endl;
}

ExprType_t
SVD::getType() const
{
  return SVD_ENUM;
}

/**
 * LU node
 */

LU::LU(const OGNumeric* arg): OGUnaryExpr{arg} {}

OGNumeric*
LU::copy() const
{
  return new LU(_args[0]->copy());
}

const LU*
LU::asLU() const
{
  return this;
}

void
LU::debug_print() const
{
  cout << "LU node" << endl;
}

ExprType_t
LU::getType() const
{
  return LU_ENUM;
}


/**
 * MTIMES node
 */

MTIMES::MTIMES(const OGNumeric* arg0, const OGNumeric* arg1): OGBinaryExpr{arg0, arg1} {}

OGNumeric*
MTIMES::copy() const
{
  return new MTIMES(_args[0]->copy(), _args[1]->copy());
}

const MTIMES*
MTIMES::asMTIMES() const
{
  return this;
}

void
MTIMES::debug_print() const
{
        cout << "MTIMES base class" << endl;
}

ExprType_t
MTIMES::getType() const
{
  return MTIMES_ENUM;
}

} // namespace librdag
