/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jvmmanager.hh>
/* Header for class com_opengamma_maths_materialisers_Materialisers */

#ifndef _Included_com_opengamma_maths_materialisers_Materialisers
#define _Included_com_opengamma_maths_materialisers_Materialisers
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_opengamma_maths_materialisers_Materialisers
 * Method:    materialiseToJDoubleArrayOfArrays
 * Signature: (Lcom/opengamma/maths/datacontainers/OGNumeric;)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_com_opengamma_maths_materialisers_Materialisers_materialiseToJDoubleArrayOfArrays
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_opengamma_maths_materialisers_Materialisers
 * Method:    materialiseToJComplexArrayContainer
 * Signature: (Lcom/opengamma/maths/datacontainers/OGNumeric;)Lcom/opengamma/maths/datacontainers/other/ComplexArrayContainer;
 */
JNIEXPORT jobject JNICALL Java_com_opengamma_maths_materialisers_Materialisers_materialiseToJComplexArrayContainer
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_opengamma_maths_materialisers_Materialisers
 * Method:    materialiseToJBoolean
 * Signature: (Lcom/opengamma/maths/datacontainers/OGNumeric;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_opengamma_maths_materialisers_Materialisers_materialiseToJBoolean
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_opengamma_maths_materialisers_Materialisers
 * Method:    materialiseToOGTerminal
 * Signature: (Lcom/opengamma/maths/datacontainers/OGNumeric;)Lcom/opengamma/maths/datacontainers/OGTerminal;
 */
JNIEXPORT jobject JNICALL Java_com_opengamma_maths_materialisers_Materialisers_materialiseToOGTerminal
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
