/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_opengamma_maths_mem_Stdlib */

#ifndef _Included_com_opengamma_maths_mem_Stdlib
#define _Included_com_opengamma_maths_mem_Stdlib
#ifdef __cplusplus
extern "C" {
#endif
#undef com_opengamma_maths_mem_Stdlib_s_addressSize
#define com_opengamma_maths_mem_Stdlib_s_addressSize 8L
/*
 * Class:     com_opengamma_maths_mem_Stdlib
 * Method:    wrapped_allocateAlignedMemory
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_opengamma_maths_mem_Stdlib_wrapped_1allocateAlignedMemory
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_opengamma_maths_mem_Stdlib
 * Method:    wrapped_freeAlignedMemory
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_opengamma_maths_mem_Stdlib_wrapped_1freeAlignedMemory
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_opengamma_maths_mem_Stdlib
 * Method:    wrapped_checkPointerSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_opengamma_maths_mem_Stdlib_wrapped_1checkPointerSize
  (JNIEnv *, jclass);

/*
 * Class:     com_opengamma_maths_mem_Stdlib
 * Method:    wrapped_incrementAddress
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_opengamma_maths_mem_Stdlib_wrapped_1incrementAddress
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
