/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_opengamma_longdog_materialisers_Materialisers */

#ifndef _Included_com_opengamma_longdog_materialisers_Materialisers
#define _Included_com_opengamma_longdog_materialisers_Materialisers
#ifdef __cplusplus
extern "C" {
#endif
  /*
   * Class:     com_opengamma_longdog_materialisers_Materialisers
   * Method:    materialise
   * Signature: (Lcom/opengamma/longdog/datacontainers/OGNumeric;)Lcom/opengamma/longdog/datacontainers/OGNumeric;
   */
  JNIEXPORT jobject JNICALL Java_com_opengamma_longdog_materialisers_Materialisers_materialise
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
