/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_opengamma_longdog_nativeloader_NativeLibraries */

#ifndef _Included_com_opengamma_longdog_nativeloader_NativeLibraries
#define _Included_com_opengamma_longdog_nativeloader_NativeLibraries
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_opengamma_longdog_nativeloader_NativeLibraries
 * Method:    getSupportedInstructionSet
 * Signature: ()Lcom/opengamma/longdog/nativeloader/SupportedInstructionSet;
 */
JNIEXPORT jobject JNICALL Java_com_opengamma_longdog_nativeloader_NativeLibraries_getSupportedInstructionSet
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
