/**
 * Copyright (C) 2013 - present by OpenGamma Inc. and the OpenGamma group of companies
 *
 * Please see distribution for license.
 */

#ifndef _EXPRESSIONBASE_HH
#define _EXPRESSIONBASE_HH

#include <memory>
#include <vector>
#include "numeric.hh"
#include "visitor.hh"

using namespace std;


/**
 * The namespace for the DAG library
 */
namespace librdag
{

/**
 * Container for expression arguments
 */

typedef vector<OGNumeric::Ptr> ArgContainer;
typedef vector<OGNumeric::Ptr> RegContainer;

/**
 *  Expr type
 */
class OGExpr: public OGNumeric
{
  public:
    typedef std::shared_ptr<const OGExpr> Ptr;
    virtual ~OGExpr();
    const ArgContainer& getArgs() const;
    RegContainer& getRegs() const;
    size_t getNArgs() const;
    virtual OGExpr::Ptr asOGExpr() const override;
    virtual void debug_print() const override;
    virtual void accept(Visitor &v) const override;
  protected:
    OGExpr();
    ArgContainer _args;
  private:
    mutable RegContainer _regs;
};

/**
 * Things that extend OGExpr
 */

class OGUnaryExpr: public OGExpr
{
  protected:
    OGUnaryExpr(OGNumeric::Ptr arg);
};

class OGBinaryExpr : public OGExpr
{
  protected:
    OGBinaryExpr(OGNumeric::Ptr arg0, OGNumeric::Ptr arg1);
};

/**
 * Non-autogenerated nodes
 */

class COPY: public OGUnaryExpr
{
  public:
    typedef std::shared_ptr<const COPY> Ptr;
    COPY(OGNumeric::Ptr arg);
    virtual OGNumeric::Ptr copy() const override;
    virtual COPY::Ptr asCOPY() const override;
    virtual void debug_print() const override;
    virtual ExprType_t getType() const override;
};

class SELECTRESULT: public OGExpr
{
  public:
    typedef std::shared_ptr<const SELECTRESULT> Ptr;
    SELECTRESULT(OGNumeric::Ptr arg0, OGNumeric::Ptr arg1);
    virtual OGNumeric::Ptr copy() const override;
    virtual SELECTRESULT::Ptr asSELECTRESULT() const override;
    virtual void debug_print() const override;
    virtual ExprType_t getType() const override;
};

class NORM2: public OGUnaryExpr
{
  public:
    typedef std::shared_ptr<const NORM2> Ptr;
    NORM2(OGNumeric::Ptr arg);
    virtual OGNumeric::Ptr copy() const override;
    virtual NORM2::Ptr asNORM2() const override;
    virtual void debug_print() const override;
    virtual ExprType_t getType() const override;
};


class PINV: public OGUnaryExpr
{
  public:
    typedef std::shared_ptr<const PINV> Ptr;
    PINV(OGNumeric::Ptr arg);
    virtual OGNumeric::Ptr copy() const override;
    virtual PINV::Ptr asPINV() const override;
    virtual void debug_print() const override;
    virtual ExprType_t getType() const override;
};

class INV: public OGUnaryExpr
{
  public:
    typedef std::shared_ptr<const INV> Ptr;
    INV(OGNumeric::Ptr arg);
    virtual OGNumeric::Ptr copy() const override;
    virtual INV::Ptr asINV() const override;
    virtual void debug_print() const override;
    virtual ExprType_t getType() const override;
};


class TRANSPOSE: public OGUnaryExpr
{
  public:
    typedef std::shared_ptr<const TRANSPOSE> Ptr;
    TRANSPOSE(OGNumeric::Ptr arg);
    virtual OGNumeric::Ptr copy() const override;
    virtual TRANSPOSE::Ptr asTRANSPOSE() const override;
    virtual void debug_print() const override;
    virtual ExprType_t getType() const override;
};

class CTRANSPOSE: public OGUnaryExpr
{
  public:
    typedef std::shared_ptr<const CTRANSPOSE> Ptr;
    CTRANSPOSE(OGNumeric::Ptr arg);
    virtual OGNumeric::Ptr copy() const override;
    virtual CTRANSPOSE::Ptr asCTRANSPOSE() const override;
    virtual void debug_print() const override;
    virtual ExprType_t getType() const override;
};


class SVD: public OGUnaryExpr
{
  public:
    typedef std::shared_ptr<const SVD> Ptr;
    SVD(OGNumeric::Ptr arg);
    virtual OGNumeric::Ptr copy() const override;
    virtual SVD::Ptr asSVD() const override;
    virtual void debug_print() const override;
    virtual ExprType_t getType() const override;
};

class MTIMES: public OGBinaryExpr
{
  public:
    typedef std::shared_ptr<const MTIMES> Ptr;
    MTIMES(OGNumeric::Ptr arg0, OGNumeric::Ptr arg1);
    virtual OGNumeric::Ptr copy() const override;
    virtual MTIMES::Ptr asMTIMES() const override;
    virtual void debug_print() const override;
    virtual ExprType_t getType() const override;
};

class LU: public OGUnaryExpr
{
  public:
    typedef std::shared_ptr<const LU> Ptr;
    LU(OGNumeric::Ptr arg);
    virtual OGNumeric::Ptr copy() const override;
    virtual LU::Ptr asLU() const override;
    virtual void debug_print() const override;
    virtual ExprType_t getType() const override;
};

} // namespace librdag

#endif // _EXPRESSIONBASE_HH
