#
# Copyright (C) 2013 - present by OpenGamma Inc. and the OpenGamma group of companies
#
# Please see distribution for license.
#

createexpr_cc = """\
/**
 * Copyright (C) 2013 - present by OpenGamma Inc. and the OpenGamma group of companies
 *
 * Please see distribution for license.
 *
 * This file is autogenerated as part of the DOGMA2 build process - src/generator/generator.py
 */

#include <sstream>
#include "expression.hh"
#include "exprtypeenum.h"
#include "exprfactory.hh"
#include "jvmmanager.hh"
#include "jterminals.hh"
#include "debug.h"

namespace convert {

using namespace librdag;

pOGNumeric translateNode(JNIEnv* env, jobject obj, pOGNumeric arg0, pOGNumeric arg1)
{
  librdag::pOGNumeric expr = nullptr;

  // Get the type of the node
  jobject typeobj = env->CallObjectMethod(obj, JVMManager::getOGNumericClazz_getType());
  checkEx(env);
  jlong type = env->GetLongField(typeobj, JVMManager::getOGExprEnumClazz__hashdefined());

  switch(type)
  {
%(switch_cases)s
  default:
  {
    stringstream s;
    s << "Unknown node type " << type;
    throw convert_error(s.str());
  }
  break;
  }

  return expr;
}

} // namespace convert
"""

terminal_case = """\
    case %(enumname)s:
      DEBUG_PRINT("Binding a J%(typename)s\\n");
      expr = pOGNumeric{new J%(typename)s(obj)};
      break;
"""

expr_case = """\
    case %(enumname)s:
      DEBUG_PRINT("%(typename)s function\\n");
      expr = pOGNumeric{new %(typename)s(%(args)s)};
      break;
"""

unary_args = "arg0"

binary_args = "arg0, arg1"
