#
# Copyright (C) 2013 - present by OpenGamma Inc. and the OpenGamma group of companies
#
# Please see distribution for license.
#

createexpr_cc = """\
/**
 * Copyright (C) 2013 - present by OpenGamma Inc. and the OpenGamma group of companies
 *
 * Please see distribution for license.
 *
 * This file is autogenerated as part of the DOGMA2 build process - src/generator/generator.py
 */

#include <sstream>
#include "expression.hh"
#include "exprtypeenum.h"
#include "exprfactory.hh"
#include "jvmmanager.hh"
#include "jterminals.hh"
#include "debug.h"

namespace convert {

using namespace librdag;

OGNumeric* createExprWithID(jlong ID, jobject obj)
{
  librdag::OGNumeric * _expr = nullptr;

  switch(ID)
  {
%(switch_cases)s
  default:
  {
    stringstream s;
    s << "Unknown node type " << ID;
    throw convert_error(s.str());
  }
  break;
  }

  if(_expr == nullptr)
  {
    throw convert_error("_expr is NULL, and probably hasn't been set by the factory");
  }

  return _expr;
}

} // namespace convert
"""

terminal_case = """\
    case %(enumname)s:
      DEBUG_PRINT("Binding a J%(typename)s\\n");
      _expr = new J%(typename)s(obj);
      break;
"""

expr_case = """\
    case %(enumname)s:
      DEBUG_PRINT("%(typename)s function\\n");
      _expr = new %(typename)s(generateArgs(obj));
      break;
"""
